name: Upstream sync

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master
          fetch-depth: 0
      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/Klipper3d/klipper.git
          git fetch upstream master
      - name: Merge changes
        id: merge
        run: |
	  echo "status=success" >> $GITHUB_OUTPUT
	  echo "tagname=master-$(date +'%y%m%d')" >> $GITHUB_OUTPUT
          git config user.name Ben Van Mierloo 
          git config user.email benvanmierloo@users.noreply.github.com
          git merge --no-commit --no-ff upstream/master
          git commit -m "Merge upstream changes" || echo "status=failure" >> $GITHUB_OUTPUT
      - name: Push changes
        if: $GITHUB_OUTPUT.status == 'success'
        run: |
          git push origin master
      - name: Create tag
        if: $GITHUB_OUTPUT.status == 'success'
        run: |
          git tag -m '/!\ This is an automated, untested release. Use at your own risk /!\' ${{ $GITHUB_OUTPUT.tagname }}
          git push origin refs/tags/${{ $GITHUB_OUTPUT.tagname }}
      - name: Create prerelease
        uses: actions/github-script@v3
        if: $GITHUB_OUTPUT.status == 'success'
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ $GITHUB_OUTPUT.tagname }}",
              prerelease: true
            })
